[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --timeout 300 --workers 2 --threads 2"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10